using Domain.SeedWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain.Aggrgates.LocationAggregate
{
    public class Location : RootEntity
    {
        // Needed for EF
        private Location(): this(null!) {}

        public Location(string portCode)
        {
            PortCode = portCode;
        }

        /// <summary>
        /// Readonly is not allowed in EF, it will be ignored (no field generated in SQL)
        /// </summary>
        public string PortCode { get; private set; }

        /// <summary>
        /// Key -> auto generated by EF
        /// </summary>
        public int LocationId { get; private set; }   
    }
}
